openapi: 3.1.0
info:
  title: Geomagnetism (Kp/Dst)
  version: "1.0.0"
servers:
  - url: https://services.swpc.noaa.gov/json
paths:
  /planetary_k_index_1m.json:
    get:
      operationId: getKp
      summary: Planetary K-index timeseries (1-minute)
      parameters:
        - { name: hours, in: query, required: false, schema: { type: integer, minimum: 1, maximum: 168 }, description: "Lookback window client-side" }
      responses:
        "200":
          description: Kp samples
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MagnetosphereObject"
components:
  schemas:
    MagnetosphereObject:
      type: object
      properties:
        ok: { type: boolean }
        kpIndex: { type: number }
        kpTrend: { type: string, enum: [rising, steady, falling] }
        dstIndex: { type: number, nullable: true }
        sources:
          type: array
          items: { type: string }
