openapi: 3.1.0
info:
  title: Space Radiation Flux
  version: "1.0.0"
servers:
  - url: https://services.swpc.noaa.gov/json/goes/eps
paths:
  /avg_proton_flux_1m.json:
    get:
      operationId: getRadiationFlux
      summary: Proton flux (1-minute averages)
      parameters:
        - { name: hours, in: query, required: false, schema: { type: integer, minimum: 1, maximum: 168 } }
      responses:
        "200":
          description: Flux snapshot
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  radiationFlux:
                    type: object
                    properties:
                      p10: { type: number, description: "Proton flux >10 MeV" }
                      p50: { type: number, nullable: true }
                      p100: { type: number, nullable: true }
                  sources:
                    type: array
                    items: { type: string }
