openapi: 3.1.0
info:
  title: USGS Earthquakes
  version: "1.0.0"
  description: Daily earthquake summary feed (GeoJSON).

servers:
  - url: https://earthquake.usgs.gov/earthquakes/feed/v1.0

paths:
  /summary/all_day.geojson:
    get:
      operationId: getEarthquakesPastDay
      summary: Earthquakes in the past 24 hours
      parameters: []
      responses:
        "200":
          description: GeoJSON feed of recent earthquakes
          content:
            application/geo+json:
              schema:
                type: object
                properties:
                  type: { type: string }
                  metadata: { type: object }
                  features:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        properties:
                          type: object
                          properties:
                            mag: { type: number }
                            place: { type: string }
                            time: { type: integer, description: "epoch ms" }
                        geometry:
                          type: object
                          properties:
                            type: { type: string }
                            coordinates:
                              type: array
                              items: { type: number }
        "4XX": { description: Client error }
        "5XX": { description: Server error }
