
name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Start API
        run: |
          nohup uvicorn orchestrator.app:app --host 0.0.0.0 --port 8000 &
          sleep 10
      - name: Run pytest integration suite
        run: |
          pytest -q tests/test_adapters.py
