name: API Health Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start API (background)
        run: |
          nohup uvicorn orchestrator.app:app --host 0.0.0.0 --port 8000 &
          sleep 8
      - name: Run health checks
        run: |
          curl -f http://localhost:8000/time/utc
          curl -f http://localhost:8000/weather/current?lat=-27.47&lon=153.03
          curl -f http://localhost:8000/quakes/past-day
          echo "✅ Live endpoints verified."
      - name: Stop API
        if: always()
        run: pkill -f uvicorn || true
