name: Validate Specs & API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Lint OpenAPI master spec
        run: redocly lint specs/observatorium.master.yaml

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import check
        run: python - << 'PY'
import importlib
import sys
for m in ["fastapi","uvicorn","requests"]:
    importlib.import_module(m)
print("Imports OK")
PY
