name: Validate Observatorium Stack

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # Secrets are injected here; the script will read them.
      NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      IQAIR_KEY: ${{ secrets.IQAIR_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      # Optional but nice: ensure the workflow files themselves are valid YAML
      - name: Lint workflow YAMLs
        run: |
          python - <<'EOF'
          import sys, yaml, pathlib
          for p in pathlib.Path(".github/workflows").glob("*.yml"):
              with p.open() as f:
                  yaml.safe_load(f)
              print(f"✓ {p} is valid YAML")
          EOF

      - name: Run Observatorium validator
        run: python scripts/validate.py
